name: Auto Publish Vlogs

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (change as you want)
  workflow_dispatch:        # also allow manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Run script
        run: python yourscript.py

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto publish vlog" || echo "No changes to commit"
          git push
